pipeline {
    agent { label 'Agent-1' }
    environment { 
        PROJECT = 'Expense'
        COMPONENT = 'Backend'
        ENV = 'prod'
        }
    options { 
        disableConcurrentBuilds() 
        timeout(time: 25, unit: 'MINUTES')
        ansiColor('xterm')
        } 

    stages {
        stage('Terraform-init'){
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'AWS-Creds') {
                        sh """
                            cd 00-vpc
                            terraform init --reconfigure
                        """
                    }
                }
            }
        }
        
    }
    post { 
        always { 
            echo 'I will always say There we go.. Hello again!'
        }
        success {
            echo 'I will say Build-Hello on Success'
        }
        failure {
            echo 'I will say Failure-Hello on Failure'
        }
        // cleanup {
        //     cleanWs() // Deletes the workspace
        // }
    }
}
