pipeline {
    agent { label 'Agent-1' }
    environment { 
        PROJECT = 'Expense'
        COMPONENT = 'Backend'
        ENV = 'prod'
        }
    options { 
        disableConcurrentBuilds() 
        timeout(time: 25, unit: 'MINUTES')
        } 

    stages {
        stage('Terraform-init'){
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'AWS-Creds') {
                        sh """
                            cd 00-vpc
                            terraform init --reconfigure
                        """
                    }
                }
            }
        }
        stage('Parallel Stages') {
            parallel {
                stage('Stage-1') {
                    steps {
                        script {
                            echo "Hello this is Stage 1 inside Parallel Stage"
                            sleep 10
                        }
                    }
                }
                stage('Stage-2') {
                    steps {
                        script {
                            echo "Hello this is Stage 2 inside Parallel Stage"
                            sleep 10
                        }
                    }
                }
            }
        }
        stage("test"){
            steps {
                script{
                    sh """ 
                    echo "Hello this is my first Jenkins pipeline Stage Test"
                    echo "Component Name is ${COMPONENT}"
                    """
                }
            }
        }
    }
    post { 
        always { 
            echo 'I will always say There we go.. Hello again!'
        }
        success {
            echo 'I will say Build-Hello on Success'
        }
        failure {
            echo 'I will say Failure-Hello on Failure'
        }
        // cleanup {
        //     cleanWs() // Deletes the workspace
        // }
    }
}
